import { BRAND } from "@/lib/metadata";
import { getAllPosts } from "@/lib/blog";

export async function GET() {
  const posts = getAllPosts();
  const lines = [
    `# ${BRAND.name}`,
    "",
    `> ${BRAND.tagline}`,
    "",
    "## What this site is",
    "",
    `${BRAND.name} is an autonomous agent platform for recurring knowledge work. It keeps shared workspace context, persistent agents, Thinking Partner, and recurring task execution inside one system.`,
    "",
    "Core concept: agents are who, tasks are what, and the user supervises a running system. Quality compounds through accumulated context, prior outputs, and feedback.",
    "",
    "## Key pages",
    "",
    `- [Home](${BRAND.url}): Autonomous AI that knows your work`,
    `- [How It Works](${BRAND.url}/how-it-works): Connect, supervise, compound`,
    `- [Pricing](${BRAND.url}/pricing): Free and Pro ($19/mo, Early Bird $9/mo)`,
    `- [FAQ](${BRAND.url}/faq): Product model, integrations, agents, and pricing`,
    `- [About](${BRAND.url}/about): Why we built a compounding autonomy model`,
    `- [Blog](${BRAND.url}/blog): Essays on context accumulation and autonomous work systems`,
    "",
    "## How yarnnn works",
    "",
    "1. Connect tools, upload files, or start from chat",
    "2. Thinking Partner turns recurring work into task definitions",
    "3. Persistent agents execute tasks and deliver outputs",
    "4. You review what changed and redirect when needed",
    "5. Context, task history, and feedback compound with each cycle",
    "",
    "## Why this differs from chat-only AI",
    "",
    "- System-level context, not prompt-only context",
    "- Persistent agents, not one-off responses",
    "- Supervised output loop, not opaque generation",
    "- Improving quality with tenure, not session resets",
    "",
    "## Platforms supported",
    "",
    "- Slack",
    "- Notion",
    "",
    "## Pricing summary",
    "",
    "- Free: 150 messages/month, 20 work credits, 2 active tasks, 1x daily sync, 5/10 sources (Slack/Notion)",
    "- Pro ($19/month, Early Bird $9/month): unlimited messages, 500 work credits, 10 active tasks, hourly sync, unlimited sources",
    "",
    "## Feeds and discovery",
    "",
    `- Blog: ${BRAND.url}/blog`,
    `- RSS: ${BRAND.url}/blog/rss.xml`,
    `- Sitemap: ${BRAND.url}/sitemap.xml`,
    `- FAQ: ${BRAND.url}/faq`,
    "",
    "## Recent blog posts",
    "",
    ...posts.slice(0, 20).map((post) => `- [${post.title}](${post.canonicalUrl}): ${post.description}`),
    "",
  ];

  return new Response(lines.join("\n"), {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
