import { BRAND, STAGE_NOTICE } from "@/lib/metadata";
// ADR-445 §6 — prices interpolate from the single source.
import { PRICE_COPY } from "@/lib/subscription/usage";
import { getAllPosts } from "@/lib/blog";

// The MCP connector — yarnnn's interop face. An agent reading this file
// learns yarnnn is reachable as a memory connector, not just a website.
const MCP_URL = "https://mcp.yarnnn.com";

export async function GET() {
  const posts = getAllPosts();
  const lines = [
    `# ${BRAND.name}`,
    "",
    `> ${BRAND.tagline}`,
    "",
    "## What this site is",
    "",
    `${BRAND.name} is a durable memory layer that sits across the AI tools you already use. What you tell one AI is remembered for the next — kept in one shared workspace you own, written by you, your teammates (invited by email), and your AIs, with full history of who changed what and when.`,
    "",
    "Core idea: your context shouldn't reset every session or live trapped inside one vendor. yarnnn holds it as authored, attributed substrate — every fact carries provenance, and you can trace how any of it changed over time.",
    "",
    "## Connect yarnnn to any AI (MCP)",
    "",
    `yarnnn exposes a Model Context Protocol (MCP) server so any MCP-capable assistant — ChatGPT, Claude, and others — can read and write your memory directly.`,
    "",
    `- MCP connector URL: ${MCP_URL}`,
    "- Auth: OAuth 2.1",
    "- Discovery: " + `${BRAND.url}/.well-known/mcp.json`,
    // ADR-635 D9 — the roster is the server's own tools/list; a copy here drifts
    // (this file advertised three retired verbs for months after ADR-543).
    "- Tools: file verbs over the shared workspace — read, search, write, move and share files, with history — every write signed as the connecting AI. The roster is the server's own tools/list; this file does not copy it.",
    "",
    "## Developer resources",
    "",
    "Everything an agent or developer needs to build on yarnnn, at predictable URLs:",
    "",
    `- Developer hub: ${BRAND.url}/developers`,
    `- OpenAPI specification (OpenAPI 3.1): ${BRAND.url}/openapi.json`,
    `- MCP connector: ${MCP_URL} (transport: streamable-http, auth: OAuth 2.1)`,
    `- MCP discovery card: ${BRAND.url}/.well-known/mcp.json`,
    `- OAuth 2.1 authorization metadata: ${MCP_URL}/.well-known/oauth-authorization-server`,
    "- API errors are structured JSON: { error: { code, message, hint } } — never HTML.",
    `- Product docs: https://yarnnn.gitbook.io/docs`,
    "",
    "## Key pages",
    "",
    `- [Home](${BRAND.url}): Shared memory for AI + human work`,
    `- [How It Works](${BRAND.url}/how-it-works): The substrate loop — capture, recall, trace`,
    `- [Pricing](${BRAND.url}/pricing): Free for two people; a paid seat per extra teammate + pay-as-you-go usage`,
    `- [FAQ](${BRAND.url}/faq): Product model, integrations, and pricing`,
    `- [Developers](${BRAND.url}/developers): API, MCP connector, OpenAPI spec, and OAuth`,
    `- [About](${BRAND.url}/about): Why we built a memory layer you own`,
    `- [Blog](${BRAND.url}/blog): Essays on durable memory and cross-LLM work`,
    "",
    "## How yarnnn works",
    "",
    "1. Connect yarnnn to your AI tools over MCP (or upload files / start from chat)",
    "2. As you work, save what's worth keeping — decisions, facts, preferences",
    "3. Any connected AI can recall that context on the next session, with provenance intact",
    "4. Trace how any fact evolved — every change is attributed and reversible",
    "5. Your memory compounds and stays portable; it never resets and you never lose ownership",
    "",
    "## Why this differs from per-tool memory",
    "",
    "- One memory across every AI, not a separate silo per vendor",
    "- One workspace across your whole team — humans and AIs write the same memory, each attributed as themselves",
    "- Authored and attributed, not an opaque embedding blob",
    "- Full change history you can trace, not a flat key-value store",
    "- Yours to own and export, not locked inside one platform",
    "",
    // ADR-629 D4 — the product's stage, from the ONE declaration.
    ...(STAGE_NOTICE ? ["## Status", "", STAGE_NOTICE, ""] : []),
    "## Platforms supported",
    "",
    "- Any MCP-capable AI (ChatGPT, Claude, and others)",
    "- Slack",
    "- Notion",
    "",
    "## Pricing summary",
    "",
    "- The workspace and your memory are free for two people — files, chat, context reachable from any AI via MCP. No feature gates.",
    `- Two pricing axes: (1) seats — the first two humans (owner + one teammate) are free; each additional human is a paid seat (${PRICE_COPY.seat}/mo); AI connections are always free and never a seat. (2) usage — pure pay-as-you-go from one shared balance the owner funds, readable line by line; top up any amount from ${PRICE_COPY.topUpMin} (top-ups never expire); hard stop at zero.`,
    "- Budget cap (separate from the plan): you set a monthly ceiling per operation and the agent paces its own work to stay under it. Two guardrails: a budget ceiling you plan, and a zero-balance floor that pauses without losing anything.",
    `- Every workspace starts with a ${PRICE_COPY.signupGrant} usage balance — enough to feel the loop before you spend a cent.`,
    "",
    "## Feeds and discovery",
    "",
    `- Developer hub: ${BRAND.url}/developers`,
    `- OpenAPI spec: ${BRAND.url}/openapi.json`,
    `- MCP connector: ${MCP_URL}`,
    `- MCP discovery card: ${BRAND.url}/.well-known/mcp.json`,
    `- Blog: ${BRAND.url}/blog`,
    `- RSS: ${BRAND.url}/blog/rss.xml`,
    `- Sitemap: ${BRAND.url}/sitemap.xml`,
    `- FAQ: ${BRAND.url}/faq`,
    "",
    "## Recent blog posts",
    "",
    ...posts.slice(0, 20).map((post) => `- [${post.title}](${post.canonicalUrl}): ${post.description}`),
    "",
  ];

  return new Response(lines.join("\n"), {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
