import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border py-4 px-6">
        <Link href="/" className="text-xl font-brand">
          yarnnn
        </Link>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-12 prose prose-neutral dark:prose-invert">
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-muted-foreground mb-8">
          <strong>Effective Date: January 28, 2026</strong>
        </p>

        <p>
          Welcome to YARNNN. By using our app or site, you agree to these Terms
          of Service. If you disagree, please do not use our services.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-4">1. Use of Services</h2>
        <p>You must:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Be 18+ years old</li>
          <li>Use the service lawfully</li>
          <li>Maintain the security of your account credentials</li>
        </ul>

        <h2 className="text-xl font-semibold mt-8 mb-4">2. User Data</h2>
        <p>When you use YARNNN, we may collect and process:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Your email address and profile information</li>
          <li>Content you upload or create (documents, blocks, projects)</li>
          <li>Work outputs generated by AI agents</li>
        </ul>
        <p>
          Your data is stored securely and used only to provide and improve our
          services. See our{" "}
          <Link href="/privacy" className="text-primary hover:underline">
            Privacy Policy
          </Link>{" "}
          for details.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-4">3. AI-Generated Content</h2>
        <p>
          YARNNN uses AI agents to generate work outputs. While we strive for
          accuracy, AI-generated content may contain errors. You are responsible
          for reviewing and verifying all outputs before use.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-4">4. Restrictions</h2>
        <p>You may not:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Use the service for illegal purposes</li>
          <li>Attempt to disrupt or reverse-engineer the platform</li>
          <li>Violate intellectual property or third-party rights</li>
          <li>Upload malicious content or malware</li>
        </ul>
        <p>Violations may result in suspension or termination of your account.</p>

        <h2 className="text-xl font-semibold mt-8 mb-4">5. Modifications</h2>
        <p>
          We may update these terms and notify you if changes are material.
          Continued use after changes means acceptance of the new terms.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-4">6. Termination</h2>
        <p>
          We may suspend or terminate your access for violating these terms or
          for any other reason at our discretion.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-4">7. Disclaimers</h2>
        <p>
          YARNNN is provided &quot;as is&quot; with no warranties. We do our best to
          ensure reliability but offer no uptime or accuracy guarantees.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-4">8. Contact</h2>
        <p>
          Questions? Contact us at{" "}
          <a
            href="mailto:admin@yarnnn.com"
            className="text-primary hover:underline"
          >
            admin@yarnnn.com
          </a>
        </p>
      </main>
    </div>
  );
}
