-- Migration 168: add source column to action_proposals — ADR-252 Phase 3
--
-- ADR-252 D5: distinguishes how a proposal was originated so the reactive
-- Reviewer dispatcher can skip re-invocation when the Reviewer already judged.
--
-- source values (nullable — NULL for legacy rows, pre-ADR-252):
--   production_agent   — proposal from a headless production agent (default)
--   reviewer_periodic  — proposal generated by Reviewer during periodic reflection (ADR-252 D6)
--   reviewer_addressed — proposal implied by Reviewer's addressed-mode assessment (ADR-252 D5)
--
-- No CHECK constraint: nullable + open-ended to allow future sources without migrations.
-- The dispatch skip logic checks for explicit reviewer_* values; NULL routes normally.

ALTER TABLE action_proposals ADD COLUMN IF NOT EXISTS source TEXT;

COMMENT ON COLUMN action_proposals.source IS
  'How the proposal was originated. NULL = legacy/production_agent (default reactive path).
   reviewer_periodic  = generated by Reviewer during periodic reflection (ADR-252 D6).
   reviewer_addressed = generated from Reviewer addressed-mode assessment (ADR-252 D5).
   production_agent   = from a headless production agent (explicit, same as NULL).
   Used by review_proposal_dispatch.on_proposal_created to skip reactive re-invocation
   when the Reviewer already rendered judgment on this proposal.';
