-- Migration 169: document reviewer_heartbeat as a valid action_proposals.source value
-- ADR-253 D5: Reviewer heartbeat mode adds a new proposal source.
--
-- The source column (added in migration 168) has no CHECK constraint — it is
-- intentionally open-ended to allow new source values without migrations.
-- This migration adds a comment documenting the full current set of valid values.
--
-- Valid source values (as of ADR-253):
--   NULL / production_agent — standard headless production agent proposal
--   reviewer_periodic       — from Reviewer periodic reflection (ADR-252 D6)
--   reviewer_addressed      — from Reviewer addressed-mode assessment (ADR-252 D5)
--   reviewer_heartbeat      — from Reviewer heartbeat mode (ADR-253 D5)

COMMENT ON COLUMN action_proposals.source IS
  'How the proposal was originated. NULL = legacy/production_agent (default reactive path).
   production_agent   = from a headless production agent (explicit).
   reviewer_periodic  = generated by Reviewer during periodic reflection (ADR-252 D6).
   reviewer_addressed = generated from Reviewer addressed-mode assessment (ADR-252 D5).
   reviewer_heartbeat = generated by Reviewer during heartbeat_turn() (ADR-253 D5).
   All reviewer_* sources skip reactive Reviewer re-invocation in on_proposal_created.';
